### ISSUE TITLE
[Feature]:  Box plots

### ISSUE THREAD

**Issue by mrporsev** [tremorlabs/tremor-npm#1098]
### What problem does this feature solve?

There is no boxplots present and it will be a good feature to add since these types of plots are widely used in HR analytics. To summarize what a boxplot is: 
"A Box Plot Series, also known as a Box-and-Whisker Plot, visually summarises a dataset's distribution through its median and quartiles." [https://charts.ag-grid.com/react/box-plot-series/].

There should be a way to create horizontal and vertical box plots.

**Comment by severinlandolt** [comment]
Hi @mrporsev! Have not used this since my data science job 5 years ago. Just had a look at recharts and they don't offer this directly. Hence, we won't add it  as well.

If I would need a box plot today, I'd probably use this one: https://g2.antv.antgroup.com/en/examples/general/box#box

Thanks for sharing and happy coding!
