### ISSUE TITLE
Feature request - Zoom/pan charts

### ISSUE THREAD

**Issue by Dakauann** [tremorlabs/tremor-npm#139]
Is there any possibility that in the future, there will be an option to add zoom and pan to charts?

**Comment by mitrotasios** [comment]
Hi @Dakauann, thanks for your comment! This is definitely something we would like to add in the future. We are are trying to find a chart library that ideally supports this out of the box.

**Comment by jschuur** [comment]
Was just looking for this one too.

Looks like recharts has [zooming](https://recharts.org/en-US/examples/HighlightAndZoomLineChart) but not panning. Recent-ish [comment](https://github.com/recharts/recharts/issues/710#issuecomment-1469068212) from the recharts maintainer suggesting it (the panning part?) wouldn't be implemented soon.

Would it maybe make sense to have some kind of generic 'you're on your own if you do this, but pass all the options directly to recharts' ability, so that whatever they support you can access when they do?

**Comment by therealbluepandabear** [comment]
> Was just looking for this one too.
> 
> Looks like recharts has [zooming](https://recharts.org/en-US/examples/HighlightAndZoomLineChart) but not panning. Recent-ish [comment](https://github.com/recharts/recharts/issues/710#issuecomment-1469068212) from the recharts maintainer suggesting it (the panning part?) wouldn't be implemented soon.
> 
> Would it maybe make sense to have some kind of generic 'you're on your own if you do this, but pass all the options directly to recharts' ability, so that whatever they support you can access when they do?

The example you linked hardly works unfortunately.

**Comment by ruth-wielinga** [comment]
I would also love to see pan/brush/zoom type features. 

[Netdata ](https://blog.netdata.cloud/all-new-netdata-cloud-charts-2-0/) use [dygraphs](https://dygraphs.com/gallery/#g/range-selector) to good effect. (javascript)

This [link ](https://my-netdata.io/dashboard.html)has some charts under the dygraph section that you can play with the pan/zoom features.

> The charts are zoomable (drag their contents to pan, shift with mouse wheel to zoom-in or zoom-out, double click to reset it)

**Comment by severinlandolt** [comment]
Hey there, this has been in consideration for long time and we decided to no implement this feature.

**Comment by frangte** [comment]
bùn
