### ISSUE TITLE
App breaks with Check the render method of "iV'

### ISSUE THREAD

**Issue by maakle** [tremorlabs/tremor-npm#151]
I am receiving a weird error when I try to run my App and access a page where the tremor components should be rendered. It used to work before on a previous version of tremor.  

Using the latest Tremor version 1.0.11 and followed the instructions in https://www.tremor.so/docs/getting-started/installation
I important tremor correct like suggested in the `_app.tsx`

<img width="1731" alt="Screen Shot 2022-10-25 at 11 34 36 AM" src="https://user-images.githubusercontent.com/16352316/197677516-7ace22b1-479f-446c-8c9e-afb45c53f772.png">

**Comment by mitrotasios** [comment]
hi @mathiasklenk. I believe that problem may be caused by to a wrong input that you have provided. Maybe try to figure out which component is causing the error by sequentially commenting them out. I suspect that the `icon` prop is spelled with a capital `I` in one of your components. The prop name was changed to a lowercase `i`. This is a small breaking change that we introduced in [v1.0.7](https://github.com/tremorlabs/tremor/releases/tag/v1.0.7). Sorry about that!

**Comment by maakle** [comment]
I think that did the trick. Thanks!

As a round of feedback, the error message wasn't very helpful. But I saw you actually put something into the release notes about that. Hence perhaps the error message could be improved. :)

Great pace you are working on this besides that!

**Comment by mitrotasios** [comment]
Yeah thats a good point, we generally need to fix our logging / error handling! Thanks :)
