### ISSUE TITLE
Can't add extra classes

### ISSUE THREAD

**Issue by nhuxhr** [tremorlabs/tremor-npm#166]
Can't add extra classes for dark mode and others!

**Comment by christopherkindl** [comment]
Hi @jsxclan, many thanks for testing our library!

Yes, pass through of other classes is a thing we highly prioritized in our feature roadmap. It is a little bit tricky as some components have a lot of children which is why it will take some time.

With the current release we strongly want to target devs who want to turn data into apps in no time and with a very opinionated design. 

If you have any other feedback, feel free to share :)

**Comment by nhuxhr** [comment]
Alright! Looking forward to it 🙂

I'll use your library for this application I'm currently working on but without dark mode, I love the UI!
