### ISSUE TITLE
Proposal to give much more customization to tremor from recharts props

### ISSUE THREAD

**Issue by angelhodar** [tremorlabs/tremor-npm#231]
# Introduction

Hey guys, I have been experimenting with an idea I had to solve an issue I told you in videomeet (#128). My issue was that i wanted to be able to show all the x axis labels for a bar chart that could have up to 20 bars. By default, recharts hides some bar labels to avoid overlap between them, and that behaivour is controlled by the [interval](https://recharts.org/en-US/api/XAxis#interval) prop. So, I just had to play a bit with the `angle`, `interval` and a few other props to get the result I wanted that you can see in the storybook example:

![imagen](https://user-images.githubusercontent.com/26228709/205677655-a2b2bcd9-2c6f-487a-bd09-5957df8fb70b.png)

![imagen](https://user-images.githubusercontent.com/26228709/205678341-d2b8795f-c8d3-413d-b792-a5c666facf11.png)

# The idea
The interesting part is how easy it was to get into there, and the potential it has to customize all the charts. First I went to the `BaseChartProps` and imported the `XAxisProps` from recharts. I just had to add that as new prop for the base type:

```ts
// Other imports
import type { XAxisProps } from "recharts"

interface BaseChartProps {
    // ...
    xAxisProps: XAxisProps
}

export default BaseChartProps;
```

Now in the `BarChart` component I just have to get it and pass the props to the `XAxis` component from recharts:

```ts
const BarChart = ({
    // rest of props
    xAxisProps = {},
  }: BarChartProps) => {
    return (
      // ...
      <XAxis hide={!showXAxis} dataKey={dataKey} /*...rest of props*/  {...xAxisProps} />
      //
    );
  };
```

So in the storybook example I just have to add this params to get the result I want:

![imagen](https://user-images.githubusercontent.com/26228709/205684792-98780e2e-1374-4bc7-b60b-f306537b7aa6.png)

This prop extensions can be encapsulated in a single type like ExtendedProps that groups all rechart components that are used across charts (`YAxis`, `CartesianGrid`, `Legend`, `Bar`, etc) and thats the one added to `BaseChartsProps`.

What do you think guys? I think its a really nice and clean way to give tremor users all the power of recharts just by forwarding some props when tremor defaults doesnt fit within a specific use case. If you think its a good idea I could try to implement it in a PR (I am having some problems with code formatting btw #186 )

**Comment by christopherkindl** [comment]
Hi @angelhodar, long time no see! ;) 

Many thanks for this input and thinking ahead. Our philosophy is to offer more default than customization. This means that the axis labels would be rotated automatically if a certain threshold is met / if labels get too dense. Those are the things we are currently trying to tackle behind the scenes.

However, I agree with your point in some ways. There will be always edge cases in which developers want to override / extend our props. We will definitely think of this in more detail.

Many thanks for the discussion and happy hacking :)

**Comment by angelhodar** [comment]
Hi @christopherkindl, I know that this implementation would interfere a bit with the main goal of tremor, but I just see it as a complement to the well-defined set of defaults that tremor provides. In my case I have had to install recharts to achieve that specific chart functionality, when in reality it is something that (with a short overview to the code) tremor could implement easily with a cheap cost in time and complexity.

**Comment by jschuur** [comment]
> However, I agree with your point in some ways. There will be always edge cases in which developers want to override / extend our props. We will definitely think of this in more detail.

I just ran into a situation where I wanted to change the [animation speed](https://recharts.org/en-US/api/Line#animationDuration), so having the ability to override the recharts defaults would have helped in this situation too.

**Comment by mitrotasios** [comment]
hey @all, thanks for all the feedback! I think it makes sense to implement/override certain properties from recharts, however, there are some points we need to consider which I'd like to share for transparency:
1. Adding too many properties bears the risk of breaking the opinionated design system and effectively becoming another low-level chart library.
2. We are considering migrating off recharts at some point as it has certain limitations and behaviours we would like to implement differently under the hood. Moreover, the package currently introduces "high severity" security vulnerabilities for which we don't know when or if they will be fixed. Bearing that in mind, we need to carefully consider which recharts-specific properties we are adding as they are potentially not available in other libraries or have different naming.
3. We are planning to substantially alter the current tremor chart API in order to make it more extensible, affecting the prop naming and component base structure, within a tremor v2 release next year (breaking change). This means that we again need to be picky about which props we add now, in order to avoid too many breaking changes in the v2.

I hope that makes sense. This does not mean that we will be rejecting the suggested features, just that we have to think a bit more about the potential implementation.

**Comment by michaelhays** [comment]
Just my two cents: I think it's very wise to keep the defaults (both in terms of design and API) very opinionated and simplistic. This was one the main things that attracted me to the project, since it's a huge time-saver, and is particularly important when it comes to the documentation and type hints provided by the library.

Of course, the end user will always need customizations, and it seems like some sort of plugin approach would be ideal to handle these cases, in a way that doesn't pollute the global namespace. I'm guessing you may be alluding to something similar with the extensibility changes coming in v2, but just wanted to provide an end user perspective :)

**Comment by mitrotasios** [comment]
@michaelhays thanks for sharing this, totally agree!
