### ISSUE TITLE
Change Select Input colors

### ISSUE THREAD

**Issue by ssoronid** [tremorlabs/tremor-npm#276]
Im inspecting ways to change some colors at tremor, could manage almost everything but i'm lacking inputs colors for example at multiselect box.

Also would be nice to have a roadmap to when classNames would be injected and also dark-mode.

**Comment by mitrotasios** [comment]
Hey @ssoronid, that's a valid point and that's something we will introduce. On the roadmap: we are currently rewriting the library to accommodate for exposing native HTML properties such as `className` and also support theming (plus some other changes). We are hoping to release this new major release by the end of Q1.

Once we have more clarity on the exact timeline we will make a more detailed announcement. Since we don't work on tremor full-time, the timeline may vary sometimes but we expect that this is feasible. Feel free to reach out if you have more questions and feedback!

**Comment by severinlandolt** [comment]
Hey! We released a new theming, addressing the problem you mentioned. Have a look here https://www.tremor.so/docs/getting-started/theming
