### ISSUE TITLE
Feature Request: Tooltip label callback on AreaChart

### ISSUE THREAD

**Issue by Joshandrews43** [tremorlabs/tremor-npm#291]
Hi all, 

Really want to make the switch from Chart.JS to this for graphs but it seems like the AreaChart is missing one key functionality we need. 

We do spend tracking and show the user month-over-month spend, and with ChartJs we use their callbacks to dynamically render both dates onto the labels. With Tremor, I now have to have generic labels that don't explicity say the data. I've attached a screenshot of what it looks like in Tremor. The legend is totally fine, but on the tooltip I should be able to hover over the 3rd and have the current period say January 3 and the previous period say December 3 to be explicit.

<img width="644" alt="Screen Shot 2023-01-25 at 6 36 10 PM" src="https://user-images.githubusercontent.com/31226916/214719388-99d69775-65ce-447e-9788-052c03f6912f.png">

**Comment by mitrotasios** [comment]
@Joshandrews43 thanks for submitting the issue, I think this is a valid point! We aim to redesign our chart API in Q2 and will definitely consider this issue. Until then we do not plan to make any fundamental changes to the current API because we want to avoid too many breaking changes. I hope you understand and sorry that we are not able to implement a address this faster!

**Comment by christopherkindl** [comment]
@Joshandrews43 Better late than never: https://lab.tremor.so/tooltip

Will be released in the next version. Let me know if you any feedback! 🙂
