### ISSUE TITLE
Feature request: TextArea

### ISSUE THREAD

**Issue by davidjgonzalez** [tremorlabs/tremor-npm#363]
It appears we only have a TextInput and not a text area component. Would it be possible add a TextArea widget that behaves similarly to TextArea to the project?

**Comment by severinlandolt** [comment]
Hello @davidjgonzalez, I appreciate your input. After considering your suggestion, we have decided against adding a `TextArea` component. This is because the demand for such a feature in a dashboard is infrequent, and creating or customizing your own text area is a manageable task.

I created a tremor-looking TextArea for you:
[[https://play.tailwindcss.com/ZelaE1qBS5](https://play.tailwindcss.com/ZelaE1qBS5)](https://play.tailwindcss.com/4Qsmfhzzlq)

**Comment by itsjavi** [comment]
The problem with css-only approach is that we don't benefit of the error and errorMessage props and other behaviours

What about the TextInput to support a new `multiline` prop?
I could contribute with a PR if you think it's a good idea @severinlandolt

**Comment by christopherkindl** [comment]
Hi @itsjavi, we just submitted this as a new feature request that can be tackled by the community. Let me know if you want to work on this! 🙂

Link to feature request: https://github.com/tremorlabs/tremor/issues/670
