### ISSUE TITLE
Support for tailwind prefix config setting

### ISSUE THREAD

**Issue by toxsick** [tremorlabs/tremor-npm#380]
Hey guys,

first of all, thanks for this great lib. I was testing it in a quite big project of mine, that is in the midst of transitioning from bootstrap to tailwind. During that time we are using a tailwind prefix (to avoid class collisions):

https://tailwindcss.com/docs/configuration#prefix

Looks to me, that tremor not respecting this tailwind setting and generates classes without the prefix right? Can this be done?

regards and thanks

**Comment by mitrotasios** [comment]
Hey, glad you enjoy the library! Unfortunately prefixes cannot be supported with the current limitations of tailwind and we haven't found a work-around yet :(

**Comment by toxsick** [comment]
Hey @mitrotasios, thanks for your answer. I am relatively new to tailwind and I don't understand the inner workings yet, but I saw that e.g. flowbite seem to work with the prefix https://flowbite.com/docs/customize/configuration/#prefix.

Could you share a little bit of insight about the current tailwind limitations, because I would love to adapt tremor, but without the prefix I will run into too many style conflicts with the bootstrap styles at the moment I think.

Thanks a lot and keep up the awesome work!

**Comment by mitrotasios** [comment]
hey @toxsick, sorry for the late response. The main issue is that the tailwind styles in our components are hard-coded (without a prefix) and it is not possible for you as a user to attach a prefix to our styles. At the same time tailwind does not support having multiple prefixes and as a result we cannot attach a custom prefix (say `tremor-`) to our classes. If we were to do this, all downstream projects would need to work with the `tremor-` prefix which is inconvenient obviously. If multiple prefixes in a single tailwind project were supported on the other hand, this would be very inefficient, because you would have multiple classes doing the same thing, i.e. `tremor-flex`, `my-flex`. So I am not sure if there is a solution to this.

**Comment by toxsick** [comment]
Hey @mitrotasios, thanks a lot for sharing this. I guess then I have to work extra hard to get rid of my prefix situation :)

regards

**Comment by abgora** [comment]
Hello @mitrotasios, I know you closed this issue some months ago but I was wondering if something change which could solve this problem? I am including tremor (which is really nice) in a legacy project which caused conflicts with bootstrap, the prefix would solve all of the problems

Thanks for this library!

**Comment by jagnani73** [comment]
Hey @mitrotasios 
Can you cook up a workaround by maybe creating a function that returns the prefix set in tailwind config and replacing all your classNames to something like `${prefix}flex`?
