### ISSUE TITLE
Date picker - single date

### ISSUE THREAD

**Issue by bart-sofomo** [tremorlabs/tremor-npm#401]
Hi,
I was able to make a workaround so when I click a date in DateRangePicker it's always giving me just a single day but is there any option to close calendar modal on click?

**Comment by mitrotasios** [comment]
@bart-sofomo currently you can only select a single day by clicking two times on the same date.

**Comment by kacper-serewis** [comment]
Would love to have `DatePicker` instead of clicking two times on `DateRangePicker`

**Comment by mitrotasios** [comment]
@K4CZP3R, that's something we are actually considering to add. Would you mind elaborating what your use-case would be in the dashboard context?

**Comment by thomasmcinnis** [comment]
I have several situations that I could put a single date picker to use immediately: User date of birth (important for my app), user access end date (for admins to schedule user termination), scheduling a future event, adding a historical event to user profile.

I am validating plain text at the moment for this, and TextInput does not expose type="date" 

(PS: I know that Tremor is designed for dashboards but it has *almost* all the features I need in my app so otherwise very happy to have one framework which is opinionated in design and includes chart and other UI)

**Comment by mitrotasios** [comment]
got it, thanks for elaborating! We'll include a Datepicker probably soon

**Comment by Michael-fore** [comment]
Seconded! would love this!

Use case is employee is entering weight into a form that is measured daily and can only be enter once for a day. using this for now tho.

` onValueChange={(e)=>{
        setDateRange([e[0],e[0]])
      }}`
