### ISSUE TITLE
Reporting Bug on MultiSelectBox

### ISSUE THREAD

**Issue by hyukkyukang** [tremorlabs/tremor-npm#422]
Hello, I found a bug with `<MultiSelectBox/>` that I would like to report. 

I am using  nextjs 13 (experimental app/ directory) and with the code below, the first SelectBoxItem that is being clicked disappears from the list. While any following clicks on the remaining items do not make them disappear.

```typescript
"use client";
const headerList = ["item1", "item2", "item3"];
export default function HeaderSelection() {
    const { selectedHeaders, setSelectedHeaders } = useHeaderContext();
    return (
        <MultiSelectBox defaultValue={selectedHeaders} onValueChange={setSelectedHeaders}>
            {headerList.map((headerName: string) => (
                <MultiSelectBoxItem key={headerName} value={headerName} text={headerName} />
            ))}
        </MultiSelectBox>
    );
}
```

The workaround that I employed was to create a clone of the array. I don't really know why this version works.
```typescript
"use client";
const headerList = ["item1", "item2", "item3"];
export default function HeaderSelection() {
    const { selectedHeaders, setSelectedHeaders } = useHeaderContext();
    // Deep copy to avoid bug on MultiSelectBox componenet
    const copiedTableHeaders: string[] = Object.assign([], selectedHeaders);
    return (
        <MultiSelectBox defaultValue={copiedTableHeaders} onValueChange={setSelectedHeaders}>
            {headerList.map((headerName: string) => (
                <MultiSelectBoxItem key={headerName} value={headerName} text={headerName} />
            ))}
        </MultiSelectBox>
    );
}
```

I am very new to tremor and believe it is a bug. However, please kindly let me know if this is intended.

**Comment by sachinmk27** [comment]
Able to reproduce [here](https://codesandbox.io/p/sandbox/reverent-julien-vq93dk)

It is probably happenning because the defaultValue prop is being mutated in the MultiSelectBox component.
This function is being called in the component
https://github.com/tremorlabs/tremor/blob/92b84bd1433c2a797e6fba02e51a54a75ef3eddb/src/lib/utils.tsx#L27

**Comment by mitrotasios** [comment]
hey @hyukkyukang, thanks for using Tremor! This is not a bug but the Select components are intended to be used differently as shown in the [docs](https://www.tremor.so/docs/components/select) in the `Controlled state example` section. In your case this would be implemented as follows:
```
"use client";
const headerList = ["item1", "item2", "item3"];
export default function HeaderSelection() {
    const [selectedHeader, setSelectedHeader] = useState("item1");
    return (
        <MultiSelectBox value={selectedHeader} onValueChange={setSelectedHeader}>
            {headerList.map((headerName: string) => (
                <MultiSelectBoxItem key={headerName} value={headerName} text={headerName} />
            ))}
        </MultiSelectBox>
    );
}
```
Note that you should use `value` instead of `defaultValue` since you are using the controlled version of the component. You can read more about controlled and uncontrolled components in React [here](https://www.geeksforgeeks.org/what-are-controlled-components-in-reactjs/).

Let me know if you face any other issue.
