### ISSUE TITLE
[Feature]: Support for custom hex colors

### ISSUE THREAD

**Issue by bgramaje** [tremorlabs/tremor-npm#565]
### What problem does this feature solve?

I would like to know if there is any possibility of supporting custom hex colors for theming the components, such as defining primary, secondary, tertiary and so on... colors.

Thanks in advance,

Regards,

Borja

**Comment by lakeesiv** [comment]
You can change the colors that `tremor` uses via the tailwind config

```js
colors: {
        // light mode
        tremor: {
          brand: {
            faint: "#eff6ff", // blue-50
            muted: "#bfdbfe", // blue-200
            subtle: "#60a5fa", // blue-400
            DEFAULT: "#3b82f6", // blue-500
            emphasis: "#1d4ed8", // blue-700
            inverted: "#ffffff", // white
          },
          background: {
            muted: "#f9fafb", // gray-50
            subtle: "#f3f4f6", // gray-100
            DEFAULT: "#ffffff", // white
            emphasis: "#374151", // gray-700
          },
          border: {
            DEFAULT: "#e5e7eb", // gray-200
          },
          ring: {
            DEFAULT: "#e5e7eb", // gray-200
          },
          content: {
            subtle: "#9ca3af", // gray-400
            DEFAULT: "#6b7280", // gray-500
            emphasis: "#374151", // gray-700
            strong: "#111827", // gray-900
            inverted: "#ffffff", // white
          },
        },
        // dark mode
        "dark-tremor": {
          brand: {
            faint: "#0B1229", // custom
            muted: "#172554", // blue-950
            subtle: "#1e40af", // blue-800
            DEFAULT: "#3b82f6", // blue-500
            emphasis: "#60a5fa", // blue-400
            inverted: "#030712", // gray-950
          },
          background: {
            muted: "#131A2B", // custom
            subtle: "#1f2937", // gray-800
            DEFAULT: "#111827", // gray-900
            emphasis: "#d1d5db", // gray-300
          },
          border: {
            DEFAULT: "#1f2937", // gray-800
          },
          ring: {
            DEFAULT: "#1f2937", // gray-800
          },
          content: {
            subtle: "#4b5563", // gray-600
            DEFAULT: "#6b7280", // gray-600
            emphasis: "#e5e7eb", // gray-200
            strong: "#f9fafb", // gray-50
            inverted: "#000000", // black
          },
        },
      },
```

**Comment by lakeesiv** [comment]
However using custom hex classes in the components such as 
```tsx
<Icon icon={CashIcon} color="#0000FF" />
```
Won't work as firsly the `color` attribute is typed to only allow the colors in the [tailwind config](https://tailwindcss.com/docs/customizing-colors), these can be changed in your tailwind config but the names have to be be the same.

It would be nice to allow for custom hex/rgb.. colors in the attributes however I don't this would be possible as tremor uses string interpolation to build the color classNames https://github.com/tremorlabs/tremor/blob/b041b1d67faed7cc8ef9cc3eb8a7c886ca61371b/src/lib/utils.tsx#L70C36-L70C36

And so tailwind wont pickup the colors and it will not be included in the CSS bundle. It could be allowed by allowing a `safelist` in the tailwind config, but this will make the bundle big. Or alternatively, you could use the same classNames in your application, but that seems like a bit of hack.

As far as using custom utility classes (`primary`, `scendary` ...) would be nice as tailwind would include them in the bundle as long as you define them in your config! However this would require modifying the `Color` type to a string, which isn't ideal caus we lose some nice intellisense

**Comment by severinlandolt** [comment]
Hi all, I know this sounds super easy initially but it gets complicated quickly. This is due to two reasons:

1. If we start supporting custom hex colors, we have to implement that in every component (consistency)
2. There is much more "color" management under the hood than it seems at the start. 

Let me give you a visual example:

**Button. Variant: Outline**
<img width="183" alt="CleanShot 2023-07-25 at 00 00 40@2x" src="https://github.com/tremorlabs/tremor/assets/41927988/a0e26541-b071-4060-89ae-50942e6af1ba">
Alright, this button is blue. So I expect to have a property color, where I can input any hex color. This won't work.
If you look very closely, there are three shades of blue involved. Note: The shades are NOT differentiated by their opacity. There's a muted blue for the ring, a subtle blue for the border, and a brand blue for the icon itself. So, what should this icon look like if I input a yellow hex code (#ffcc33)? Should only the mailbox icon become yellow? How about the border and the ring? Should we add a function that calculates those shades? If so, what happens if you input some extreme value like a super bright yellow?

We do this because we want to ensure if you use one of our 20+ colors, you get a nice and usable icon. This rings true for the icons, but also for the more complex components where color is involved (e.g. charts, progress bars, etc.)

**Comment by bgramaje** [comment]
Hi all,

Before anything else, thank you for your responses to this topic. Really appreciate them all.

Regarding the theming of tailwind, I already know it, but the main issue I have is that I am building a metrics package that exports several charts that are customizable.

I use charts from recharts and other charts packages. I found this package with lots of usefull utilites, and I wanted to add it to the library, trying to extend the options used in my package such as 

````json
"colors":  {
     "primary" : "#000000",
     "secondary": "#FFFFFF",
} 
````

With the tailwind config I can't modify the theme "in-situ" since it compiles before the application starts.  So I was wondering if there is a way of supporting custom hex colors.

Regarding @severinlandolt  response, I understand the complexity you are mentioned, but you could start with some basic components such as line charts or area charts where you can only define the color of one datakey of the charts and so on.

But thanks for your responses!

**Comment by adamhenson** [comment]
I'm also experiencing a similar issue in which the Tailwind theme I use has custom colors. This could be a separate issue (any opinions?).

Currently I can only only use `indigo` (and other Tailwind base colors) and I cannot use custom colors or shades like `indigo-bright-600`.

```jsx
<LineChart {...props} colors={["indigo"]} />
```

I see the issue is that the types are limited to an explicit list of colors. I'm guessing there is more to it than that, but I'm wondering if there are plans to support custom and shaded theme colors (and even hex colors per this original post).

https://github.com/tremorlabs/tremor/blob/1744e4dda4562d17e74947c5e2804578677177ed/src/lib/inputTypes.ts#L35-L58

**Comment by severinlandolt** [comment]
Hi @adamhenson, we are planning to allow custom hex colors in our charts. For all other components, we will stick with our set of 22 base colors + the configurable brand color in the tailwind.config.

This is due to 5-6 associated colors for like hover, ring and other parts of components.

**Comment by adamhenson** [comment]
Thanks @severinlandolt! Any idea on when the custom hex colors in charts support could land? If not soon, any advice for someone to contribute? If I can find some time, I may be able to create a PR in this effort... unless you think I'd need a lot of core contributor knowledge.

**Comment by adamhenson** [comment]
I took a shot at one approach in supporting custom colors (custom theme colors or hex colors) in #836.
