### ISSUE TITLE
[Bug]: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [tremorlabs/tremor-npm#661]
### Tremor Version

latest

### Link to minimal reproduction

https://www.tremor.so/

### Steps to reproduce

Go to the footer section and see Twitter old logo 

### What is expected?

Twitter logo should be changed to X 

### What is actually happening?

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

### Screenshot

<img width="960" alt="Screenshot 2023-09-07 174553" src="https://github.com/tremorlabs/tremor/assets/91591901/d428d58b-298e-43fc-8987-d8a39cb4966b">

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

Won't change anything in the code as such would replace the twitter-logo.png with a new file. No code will be touched.

@christopherkindl
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by christopherkindl** [comment]
Hi @lalitkumawat1m, thanks for the hint! And yes, the time has come for us to move away from the old "Twitter" logo. Unfortunately, the website is not open-source which is why we don't take contributions there. But I can recommend you to regularly check our repo here, as we are currently working on many issues together with the community 🙂
