### ISSUE TITLE
unable to import tremor.css

### ISSUE THREAD

**Issue by rmrbytes** [tremorlabs/tremor-npm#72]
Hello:

In an existing next.js project, I am trying to import the tremor.css as per your documentation but received an error.

I first added the tremor npm using `npm install @tremor/react`

Then, I tried importing the css using `import '@tremor/react/dist/esm/tremor.css';`

Then, for a bit nothing seems to have and the cursor changes till finally I get the following message:
```
import-im6.q16: attempt to perform an operation not allowed by the security policy `@tremor/react/dist/esm/tremor.css' @ error/blob.c/OpenBlob/2624.```

I tried importing a Card in the component while it does not give me an error, it as expected did not apply the css

Thanks

**Comment by rmrbytes** [comment]
Just FYI. I was already using tailwind and the global.css of the project has

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

In which case is the tremor.css still required?

**Comment by mitrotasios** [comment]
hi @rrrepos, thanks for your comment. Which machine/OS are you using?

**Comment by rmrbytes** [comment]
> hi @rrrepos, thanks for your comment. Which machine/OS are you using?

Linux Mint 20.2 on a HP Notebook

**Comment by mitrotasios** [comment]
Hi! I tried to reproduce the issue by setting up a Docker image with Next and Tremor installed on a Linux **Alpine**  distribution, as I could not find a suitable base image for Mint. 

I created [this repository](https://github.com/mitrotasios/tremor-next-docker) and it seems to work fine, please feel free to clone the repo and try it out yourself. Note, that the `main` branch does **not** involve Tailwind, if you'd like to try out the container with Tailwind installed as well, please checkout the `with-tailwind` branch. 

Regarding your question on Tailwind: yes, even if Tailwind is already set up in your project, importing `tremor.css` is necessary. However, it is generally **not required** to have Tailwind set up in order to run Tremor.

We are exporting a `tremor.css` file in our package since we found that to be the only viable solution so far to seamlessly run a server-side rendered application with Tremor. Exporting a CSS file is not optimal because it disables tree-shaking, so we are working on figuring out a more scalable solution in the future.

Sorry that I can not help you out further with this issue at this point. I will try to look into it in the upcoming days!

**Comment by rmrbytes** [comment]
Thanks @mitrotasios . I appreciate the effort that you took. I will clone your directory or even may try out a new project to confirm the success of using tremor before I investigate why it didnt work in an existing project. I will update my findings on this issue. Thanks

**Comment by rmrbytes** [comment]
It just worked !  ... even in my existing project. Must have made some stupid error. Thanks
