### ISSUE TITLE
Use children prop instead of text

### ISSUE THREAD

**Issue by LucasAlda** [tremorlabs/tremor-npm#81]
Hi, 
First of all, congratulations, because a library like this one is something that the web community has never accomplished correctly and yours is awesome.

I noticed that in a lot of components (such as buttons, text, etc.), there is a text prop instead of simply using the children. This way is more aligned with JSX and the React philosophy and would allow some personalization without compromising much of your architecture.

Also, I love your design system, but I think the configuration given is really strange, passing tailwind classes in a separate prop instead of just having a className prop that overwrites your default classes (there are plenty of npm modules for this).

**Comment by malakhov-dmitrii** [comment]
Strongly agree about this one!
If this project has plans to grow, className and children is 100% must have (otherwise why do we even need to install tailwind, and now I need to use div wrappers even for basic styles adjustments)

**Comment by mitrotasios** [comment]
Hi, thanks a lot for the comments. Totally agree on the point about the children, we will fix this soon.

Regarding the `className`, this is definitely something we do consider for the next major release as well, given the amount of comments it got. As mentioned in other comments, the initial idea had been to provide a limited amount of props per component with a relatively low degree of customisation, in order to "enforce" an opinionated design to the end-user, which enables a fast development workflow. But we will re-evaluate the degree of customisation.

Please note, installing tailwind is **not** required to run tremor, it is listed as a devDependency.

@LucasAlda @Hennessy811 that is not a great dev-experience indeed, may I ask what kind of adjustments you are looking for? Would you also mind if we reach out to you in the future for feedback on the library? It would help us a lot!

**Comment by LucasAlda** [comment]
I totally agree with the idea of giving an opinionated design to the end-user without any complexity, and that's why my proposal is the ability to overwrite the default ones.

Example: The Text component className is "tr-shrink-0 tr-mt-0 tr-text-left tr-text-gray-500 tr-text-sm tr-font-normal"
<Text className="tr-mt-2" />
"tr-mt-2" replaces "tr-mt-0," allowing for simple and flexible configuration without redefining all of the great styles you've already added. 

PD: check [https://www.npmjs.com/package/tailwind-merge](https://www.npmjs.com/package/tailwind-merge) recommended on twitter by @tannerlinsley

**Comment by LucasAlda** [comment]
Also it hasn't need to be called "classNames", can be something more descriptive and in cases where you have multiple nested components there can be multiple props ('legend-...', 'axes-...', 'footer-...', 'label-...')
