### ISSUE TITLE
[Feature]: Sankey chart

### ISSUE THREAD

**Issue by chaos87** [tremorlabs/tremor-npm#851]
### What problem does this feature solve?

I need to create a Sankey chart in my react app.

Currently using Highcharts, but I can see how it would be nice to have the option in Tremor so it fits natively

**Comment by severinlandolt** [comment]
Hey @chaos87, I have to say no to the proposal due to:

* This chart type is not well suited to work with the simple philosophy how Tremor charts should work. There are so many use-case specific nuances, that a generalised version does not provide the value we would like to provide.
* We worked several years in data viz field and not a single production app used a Sankey chart, even if this was considered in the process.

**Comment by FleetAdmiralJakob** [comment]
Hi, I understand if you don't want to implement Sankey charts into Tremor if they don't follow your philosophy but for your second point I can tell you that there are apps out there that use them.

https://www.finanzfluss.de/copilot/

<img width="496" alt="Image" src="https://github.com/user-attachments/assets/7d9fa3ac-1645-4105-aee1-8d99a4f8582e" />

I myself want to use a Sankey Chart for my own financial app and that this thing was already requested twice shows that there is at least a little bit of interest into it.

But ofc this could be a bit of a niche feature for the finance sector and not many people would use it.

Thank you for responding so quickly. I love Tremor. Keep the work up.
