### ISSUE TITLE
[Bug]: showAnimation not working in ProgressCircle and CategoryBar's Marker

### ISSUE THREAD

**Issue by kronos1345** [tremorlabs/tremor-npm#882]
### Tremor Version

^3.12.1

### Link to minimal reproduction

-

### Steps to reproduce

- Implement a ProgressCircle or CategoryBar with the showAnimation property set to true.
- Render the component on a page.
- Observe the behavior of the animation in the specified components.

### What is expected?

The showAnimation property should enable animation in the ProgressCircle and the marker of the CategoryBar. This animation is expected to visually indicate progress or category selection dynamically, enhancing user interaction and experience.

### What is actually happening?

The showAnimation property does not trigger any animation in the ProgressCircle or the CategoryBar's marker. Despite being set to true, the components remain static, lacking the intended visual feedback of progress or selection.

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

### Any additional comments?

This inconsistency in behavior could lead to a less engaging user interface. Further investigation might be needed to determine if the problem is browser-specific or related to the component's implementation in the Tremor framework.

**Comment by severinlandolt** [comment]
Thanks @kronos1345, will take a look at this in the next release. cf. #821

**Comment by kronos1345** [comment]
This is valid for all other components. Showanimations do not work on some components. Needs general control. Thank you from now @severinlandolt . I'm looking forward

**Comment by niall-forrest** [comment]
any update on this? :)

**Comment by severinlandolt** [comment]
**ProgressCircle** (v3.17.3): Animation works for me. Note that there is no initial animation when the component is mounted. Animation is only affecting when a value changes.

https://github.com/tremorlabs/tremor/assets/41927988/cfcf2706-449c-457e-9179-1244f2574db2

**CategoryBar** (v3.17.3): Marker animation works for me also.

https://github.com/tremorlabs/tremor/assets/41927988/346c11d8-9abe-4992-aec0-beabd85c9be8

Same for Deltabar, MarkerBar, and ProgressBar.

If your issue was regarding a missing initial animation, please let me know.

Closed until more info is provided.
