### ISSUE TITLE
[Feature]: Timeline component

### ISSUE THREAD

**Issue by kolosovvs** [tremorlabs/tremor-npm#956]
Hi, we are developing a status page application and we really need a component similar to this one: https://mui.com/material-ui/react-timeline/. 
We are going to use it to create an incident history. 
It would be great if you could create a similar component. 
Thanks

**Comment by severinlandolt** [comment]
Hey @kolosovvs, thank you for your feature idea. Having looked at the example, we don't think we'll add this as component. Because those Feed/Timeline components come in a thousand different shapes, this is something we moved to our copy&paste code. You can find it here: https://blocks.tremor.so/blocks/onboarding-feed, especially  [Feed #5](https://blocks.tremor.so/blocks/onboarding-feed#onboarding-feed-5)
